"""Extract Archipelago data tables from Cairn's Il2CppDumper output.

Parses dump.cs for the game's stable ID enums and generates
ap/apworld/cairn/data.py — the single source of truth for the apworld's
item and location tables.

ID scheme (shared, by construction, with the game-side mod):
    AP item id     = ITEM_BASE + InventoryItemStringIdEnum value
    AP location id = LOCATION_BASE + StoryEventSensorStringIdEnum value
The mod never needs a lookup table: it converts ids with arithmetic.

Usage: python extract_ap_data.py
"""

from __future__ import annotations

import re
from pathlib import Path

PROJECT = Path(__file__).resolve().parents[2]
DUMP_CS = PROJECT / "dump" / "dump.cs"
OUT_DATA_PY = PROJECT / "ap" / "apworld" / "cairn" / "data.py"

ITEM_BASE = 71_110_000
LOCATION_BASE = 71_120_000

# Items that must never enter the multiworld pool: debug/test artifacts and
# story-quest items the game grants through scripted events.
EXCLUDED_ITEM_PREFIXES = (
    "ITEM_AA_DEBUG",
    "ITEM_INTERACTION_TEST",
    "ITEM_SELF_DRINK_FROM_SOURCE",
    "ITEM_MAP_",          # quest maps
    "ITEM_GABROB_",       # quest chain
    "ITEM_WEATHER_DOLL",  # quest chain
    "ITEM_RODANNA_LETTER",
    "ITEM_DRAWING_",
    "ITEM_CAMERA_BROKEN",
    "ITEM_WINDMILL",
    "ITEM_HONEY_POT_RECIPE",
    "ITEM_READABLES_BOOK",
    "ITEM_FLYER_BOOSTS",
    "ITEM_UNDERGROUND_OAK",
    "ITEM_EDELWEISS",
    "ITEM_CLIMBOT",
    "ITEM_MONEY",
)

# Name fragments → pool category. First match wins; order matters.
USEFUL_FRAGMENTS = (
    "PITON",
    "PUFF",
    "GLOWING_GLOVES",
    "SURVIVAL_BLANKET",
    "BAROMETER",
    "HEATER",
    "LIGHT_STICK",
    "CLIMBING_TAPE",
    "ADRENALINE",
    "HYDRATION_PACK",
    "THERMOS",
)


def read_enum(source: str, enum_name: str) -> dict[str, int]:
    """Return {member_name: value} for a `public enum <name>` block in dump.cs."""
    match = re.search(
        rf"^public enum {re.escape(enum_name)}\b.*?^{{(.*?)^}}",
        source,
        re.MULTILINE | re.DOTALL,
    )
    if not match:
        raise SystemExit(f"enum {enum_name} not found in {DUMP_CS}")
    members = {}
    for name, value in re.findall(
        rf"public const {re.escape(enum_name)} (\w+) = (-?\d+);", match.group(1)
    ):
        members[name] = int(value)
    return members


def display_item_name(enum_name: str) -> str:
    """ITEM_PEANUT_BUTTER -> 'Peanut Butter'."""
    return enum_name.removeprefix("ITEM_").replace("_", " ").title()


SENSOR_RE = re.compile(r"^_(\d{2})(\d{3})_(.+)$")


def display_sensor_name(enum_name: str, code: str, label: str) -> str:
    """_02010_FirstLanding -> '02010 FirstLanding'.

    The label is kept verbatim: enum names are unique and this transform is
    injective, so display names stay unique (prettifying collapses pairs like
    CableCar_Top / CableCarTop).
    """
    return f"{code} {label}"


def classify_item(name: str) -> str:
    if any(fragment in name for fragment in USEFUL_FRAGMENTS):
        return "useful"
    return "filler"


def main() -> None:
    source = DUMP_CS.read_text(encoding="utf-8", errors="replace")

    items = read_enum(source, "InventoryItemStringIdEnum")
    sensors = read_enum(source, "StoryEventSensorStringIdEnum")

    item_rows = []
    seen_values: dict[int, str] = {}
    for name, value in sorted(items.items(), key=lambda kv: kv[1]):
        if name == "None" or name.startswith(EXCLUDED_ITEM_PREFIXES):
            continue
        if value in seen_values:  # enum aliases would corrupt the id scheme
            raise SystemExit(f"duplicate item value {value}: {seen_values[value]} / {name}")
        seen_values[value] = name
        item_rows.append((display_item_name(name), name, value, classify_item(name)))

    sensor_rows = []
    zones: set[str] = set()
    for name, value in sorted(sensors.items(), key=lambda kv: kv[1]):
        match = SENSOR_RE.match(name)
        if not match:
            continue  # technical/unnumbered sensors are not v1 locations
        zone, sub, label = match.groups()
        code = zone + sub
        zones.add(zone)
        sensor_rows.append((display_sensor_name(name, code, label), name, value, zone))

    display_names = [row[0] for row in sensor_rows]
    duplicates = {n for n in display_names if display_names.count(n) > 1}
    if duplicates:
        raise SystemExit(f"non-unique location display names: {duplicates}")

    lines = [
        '"""GENERATED by ap/tools/extract_ap_data.py — do not edit by hand."""',
        "",
        f"ITEM_BASE = {ITEM_BASE}",
        f"LOCATION_BASE = {LOCATION_BASE}",
        "",
        "# (display name, game enum name, game enum value, pool category)",
        "GAME_ITEMS = [",
        *(f"    {row!r}," for row in item_rows),
        "]",
        "",
        "# (display name, game enum name, game enum value, zone)",
        "STORY_SENSORS = [",
        *(f"    {row!r}," for row in sensor_rows),
        "]",
        "",
        f"ZONES = {sorted(zones)!r}",
        "",
    ]
    OUT_DATA_PY.parent.mkdir(parents=True, exist_ok=True)
    OUT_DATA_PY.write_text("\n".join(lines), encoding="utf-8")

    print(f"items: {len(item_rows)} (of {len(items)} enum members)")
    print(f"story sensor locations: {len(sensor_rows)} (of {len(sensors)})")
    print(f"zones: {sorted(zones)}")
    print(f"wrote {OUT_DATA_PY}")


if __name__ == "__main__":
    main()
